name: python-flask-docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: docker pull
      run: |
        docker pull lvthillo/python-flask-docker
    - name: docker run
      run: |
        docker run --name my-container -d -p 8080:8080 lvthillo/python-flask-docker
    - name: docker output IP  
      run: |
        docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my-container
    - name: docker output  hostname
      run: |
        docker inspect -f '{{ .Config.Hostname }}' my-container
