name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: workflows/checkout@v2
    - name: docker push
      run: |
        docker push lvthillo/python-flask-docker
        
